---
# Source database configuration
source:
  jdbcUrl: jdbc:sqlserver://localhost:1433;database=OldDatabase;encrypt=true;trustServerCertificate=true;
  username: admin
  password: admin
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  hikari:
    connectionTimeout: 30000
    maximumPoolSize: 10

# Destination database configuration
destination:
  jdbcUrl: jdbc:sqlserver://localhost:1433;database=NewDatabase;encrypt=true;trustServerCertificate=true;
  username: admin
  password: admin
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  hikari:
    connectionTimeout: 30000
    maximumPoolSize: 10
...